ALTER TABLE Produto ADD (QtdEstoq NUMBER(5));

UPDATE Produto
SET QtdEstoq = 100;

CREATE OR REPLACE PROCEDURE Verifica_Estoque(PCOD NUMBER, PQTDE_RET NUMBER)
AS
	E_ESTOQUE EXCEPTION; --DEFINIÇÃO DO ERRO
	VQTD Produto.QtdEstoq % TYPE;
BEGIN
	SELECT QtdEstoq INTO VQTD FROM Produto
	WHERE Cod_Produto = PCOD;
	
	IF VQTD < PQTDE_RET THEN
		RAISE E_ESTOQUE; --CHAMADA DO ERRO
	ELSE
		UPDATE Produto
		SET QtdEstoq = QtdEstoq - PQTDE_RET
		WHERE Cod_Produto = PCOD;
	END IF;
	COMMIT;
	
	EXCEPTION
		WHEN NO_DATA_FOUND THEN
			INSERT INTO Tab_Erro VALUES(SYSDATE, 'Produto não existe!');
		
		WHEN E_ESTOQUE THEN --TRATAMENTO DO ERRO
			ROLLBACK;
			INSERT INTO Tab_Erro VALUES(SYSDATE, 'Estoque Insuficiente!');
END;

BEGIN
	Verifica_Estoque(1, 20);
END;